### ISSUE TITLE
1.1.3.2. Column Web-Beam Web (CWBW) connectivity

### ISSUE THREAD

**Issue by am-ru** [AjinkyaDahale/Osdag#9]
Sample Problem 2
2024-12-12 13:44:18 - Osdag - INFO - 3rows 1columns 20.0mm diameter bolts needs leg length of 86.0
2024-12-12 13:44:18 - Osdag - INFO - Available width is 80.0
2024-12-12 13:44:18 - Osdag - ERROR - The connection cannot be designed with provided bolt diameters or cleat angle list

**Comment by am-ru** [comment]
diameter, property class and thickness needs to be changed all instead of customize
currently in the input that's not working , dia- 16,property class is 4.6,thick- 16.

**Comment by AjinkyaDahale** [comment]
If this is from the output log, the "ERROR" basically just means the parameters provided fail the standard. This means that the output is consistent with the [expected values](https://static.fossee.in/html_page/DesignReport_1.1.3.2.2.pdf), and thus our _test_ has passed.

![Screenshot From 2024-12-21 17-02-59](https://github.com/user-attachments/assets/aa003603-0b7b-4567-a65f-d29b0552f2f3)

**Comment by parthckaria** [comment]
This looks correct to me @AjinkyaDahale
